<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('Yanic Show '. $this->translate('Máxima Diversión'))->setSeparator(' - ')->setAutoEscape(false) ?>
	
	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	
	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.yanic.icon', 'href' => $this->basePath() . '/img/yanic.ico'))
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
		->prependStylesheet($this->basePath('css/dashboard.css'))
		->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
	
	<!-- Scripts -->
	<?php echo $this->headScript()

		->prependFile($this->basePath('js/admin_module/adminActions.js'))
		->prependFile($this->basePath('js/admin_module/requests/adminRequest.js'))
		->prependFile($this->basePath('js/bootstrap.min.js'))
		->prependFile($this->basePath('js/jquery.min.js'))
// 		->prependFile($this->basePath('js/jquery/jquery-1.7.1.min.js'))
		->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
	; ?>

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Máxima Diversión</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">Inicio</a></li>
					<li><a href="#">Menú</a></li>
					<li><a href="#">Galeria</a></li>
					<li><a href="#">Redes Sociales</a></li>
				</ul>
				<form class="navbar-form navbar-right">
					<input type="text" class="form-control" placeholder="Search...">
				</form>
			</div>
		</div>
	</div>
	
	<div class="container-fluid">
		<div class="row">
			<div id="admin_lists" class="col-sm-3 col-md-2 sidebar">
				<ul id="home_list" class="nav nav-sidebar">
				</ul>

				<ul id="login_list" class="nav nav-sidebar">
				</ul>
				
				<ul class="nav nav-sidebar" id="logout">
					<li class="menu" id="logout_list"></li>
				</ul>
				
			</div>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<?php echo $this->content; ?>
				<hr>
				<footer>
					<p>&copy; 2005 - <?php echo date('Y') ?> Máxima Diversión. <?php echo $this->translate('All rights reserved.') ?></p>
				</footer>
			</div> <!-- /container -->
		</div>
	</div>
	
	<?php echo $this->inlineScript() ?>
</body>
</html>
