<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('Yanic Show '. $this->translate('Máxima Diversión'))->setSeparator(' - ')->setAutoEscape(false) ?>
	
	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	
	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.yanic.icon', 'href' => $this->basePath() . '/img/yanic.ico'))
		->prependStylesheet($this->basePath('css/2column.css'))
		->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
		->prependStylesheet($this->basePath('css/dashboard.css'))
// 		->prependStylesheet($this->basePath('css/social_timeline/dpSocialTimeline.css'))
// 		->prependStylesheet($this->basePath('css/social_timeline/magnific-popup.css'))
// 		->prependStylesheet($this->basePath('css/social_timeline/styles.css'))
		->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
	
	<!-- Scripts -->
	<?php echo $this->headScript()
// 		->prependFile($this->basePath('js/social_timeline/jquery.magnific-popup.min.js'))
// 		->prependFile($this->basePath('js/social_timeline/jquery.dpSocialTimeline.js'))
// 		->prependFile($this->basePath('js/social_timeline/jquery.isotope.min.js'))

		->prependFile($this->basePath('js/home_module/actions.js'))
		->prependFile($this->basePath('js/home_module/requests/home.js'))
		->prependFile($this->basePath('js/bootstrap.min.js'))
		->prependFile($this->basePath('js/jquery.min.js'))
		->prependFile($this->basePath('js/jquery-2.1.0.min.js'))
// 		->prependFile($this->basePath('js/jquery/jquery-1.7.1.min.js'))
		->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
	; ?>

</head>
<body>
	<!-- -------------- /.navbar -------------- -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">YanicShows</a>
		</div>

		<!-- -------------- Collect the nav links, forms, and other content for toggling -------------- -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="#">INICIO</a>
				</li>
				<li>
					<a data-toggle="modal" href='#infantil'>SHOWS INFANTILES</a>
				</li>
				<li>
					<a data-toggle="modal" href='#imitador'>IMITADORES</a>
				</li>
				<li>
					<a href="#">PUBLICIDAD</a>
				</li>
				<li>
					<a href="#">EVENTOS ESPECIALES</a>
				</li>
				<li>
					<a href="sections/galleria.html">GALERIA</a>
				</li>
			</ul>
		</div>
		<!-- -------------- /.navbar-collapse -------------- -->

	</nav>
	<!-- -------------- /.navbar -------------- -->
	
	<div class="jumbotron">
		<div class="container">
			<h1><span class="label ">Bienvenido!</span></h1>
			<p>
				<h3>
					<span class="label ">Si lo que buscas es el mejor</span>
					<span class="label ">entretenimiento para tus fiestas</span>
					<span class="label ">aquí lo vas a encontrar!</span>
				</h3>
			</p>
		</div>
	</div>
	
	<div class="container">
		<?php echo $this->content; ?>
				
		<div class="row">
				
				
			<div class="col-md-5">
				<div class="blog-post"><!-- -------------- /.blog-post -------------- -->
					<div class="col-md-6">
<!-- 						<h2 class="">¿Quienes Somos?</h2> -->
						<div id="home_title_0"></div>
						<p id="post-datde" class=""></p>
<!-- 						<p class="">Mayo 1, 2015 por <a href="#">Abner Showman</a></p> -->
					</div>
					<div class=" ">
						<img class="img-thumbnail medium" src="img/profile_image/logo_formal_profile_size.jpg" >
					</div>
					<hr>
					
					<div id="home_text_0">
					</div>
					
				</div><!-- -------------- /.blog-post -------------- -->
			</div>

			<div class="col-md-7">
				<div class="blog-post"><!-- -------------- /.blog-post -------------- -->
					<div class="col-md-5">
						<img class="img-thumbnail short" src="img/galeria/eventos_especiales/big_26.jpg" >
						<br>
						<br>
						<br>
						<br>
						<h2 class="">Contamos con el mejor servicio</h2>
					</div>
					<div class="col-md-7">
						<img class="img-thumbnail" src="img/galeria/eventos_especiales/big_31.jpg" >
					</div>
					<div>
						<blockquote>
							<p>
								<p>Porque sabemos que tu mereces lo mejor estamos empeñados a dar mas del <strong> 200% </strong> en cada una de nuestra presentaciones.</p>
							</p>
						</blockquote>
					</div>
				</div><!-- -------------- /.blog-post -------------- -->
			</div>
		</div>

		<div class="row">
			<div class="col-md-7">
				<img class="img-thumbnail " src="img/galeria/imitadores/big_1_medium.jpg">
			</div>
			<div class="col-md-5">
				<div class="blog-post"><!-- -------------- /.blog-post -------------- -->
					<h2 class="">Contactanos</h2>
					<ul class="nav nav-tabs nav-stacked social-buttons">
						<li>
							<a class="btn btn-block btn-social btn-lg btn-facebook" 
							href="https://www.facebook.com/pages/Yanicshow-Publicidad-y-Espectaculos/115869311875508">
								<i class="fa fa-facebook"></i>yanicshow espectaculos
							</a>
						</li>
						<li>
							<a class="btn btn-block btn-social btn-lg btn-youtube" 
								href="https://www.youtube.com/user/yanicshows"><i class="fa fa-youtube-play"></i>yanicshows</a>
						</li>
						<li>
							<a class="btn btn-block btn-social btn-lg btn-phone">
								<i class="fa fa-phone"></i>Teléfono: 63542086 <i class="fa fa-whatsapp"></i>
							</a>
						</li>
						<li>
							<a class="btn btn-block btn-social btn-lg btn-phone">
								<i class="fa fa-phone"></i>Teléfono: 46172530 <i class="fa fa-whatsapp"></i>
							</a>
						</li>
						<li>
							<a class="btn btn-block btn-social btn-lg btn-phone"></i>id: 92*962509*2</a>
						</li>
					</ul>
					<hr>
					<h3>No olvides comentar o regalarnos un like </h3>
					<div class="fb-comments" data-href="https://www.facebook.com/Yanicshow-Maxima-Diversion-115869311875508/?fref=ts" data-width="100%" data-numposts="5"></div>
				</div><!-- -------------- /.blog-post -------------- -->
			</div>
		</div>
				
		<hr>
		<footer>
			<p>&copy; 2005 - <?php echo date('Y') ?> Máxima Diversión. <?php echo $this->translate('All rights reserved.') ?></p>
		</footer>
	</div> <!-- /container -->
	
	<script type="text/javascript">
					
		/**
		 * Variable para llamado a peticiones jquery 
		 */
		var $basePath = "<?php echo $this->basePath();?>";
		
// 		$(document).ready(function(){
			
// 			$('#socialTimeline').dpSocialTimeline({
// 				feeds: 
// 				{
// 					'facebook_page': {data: '115869311875508'}
// 				},
// 				layoutMode: 'columns',
// 				showLayout: false,
// 				itemWidth: 200,
// 				total: 10
// 			});
			
// 		});
						
					</script>
	
	<?php echo $this->inlineScript() ?>
</body>
</html>
