<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('Yanic Show '. $this->translate('Máxima Diversión'))->setSeparator(' - ')->setAutoEscape(false) ?>
	
	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	
	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.yanic.icon', 'href' => $this->basePath() . '/img/yanic.ico'))
		->prependStylesheet($this->basePath('css/blog.css'))
		->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
		->prependStylesheet($this->basePath('css/dashboard.css'))
// 		->prependStylesheet($this->basePath('css/social_timeline/dpSocialTimeline.css'))
// 		->prependStylesheet($this->basePath('css/social_timeline/magnific-popup.css'))
// 		->prependStylesheet($this->basePath('css/social_timeline/styles.css'))
		->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
	
	<!-- Scripts -->
	<?php echo $this->headScript()
// 		->prependFile($this->basePath('js/social_timeline/jquery.magnific-popup.min.js'))
// 		->prependFile($this->basePath('js/social_timeline/jquery.dpSocialTimeline.js'))
// 		->prependFile($this->basePath('js/social_timeline/jquery.isotope.min.js'))

// 		->prependFile($this->basePath('js/home_module/actions.js'))
// 		->prependFile($this->basePath('js/home_module/requests/home.js'))
		->prependFile($this->basePath('js/bootstrap.min.js'))
		->prependFile($this->basePath('js/jquery.min.js'))
		->prependFile($this->basePath('js/jquery-2.1.0.min.js'))
// 		->prependFile($this->basePath('js/jquery/jquery-1.7.1.min.js'))
		->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
	; ?>

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Máxima Diversión</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">Inicio</a></li>
					<li><a href="#">Menú</a></li>
					<li><a href="#">Galeria</a></li>
					<li><a href="#">Redes Sociales</a></li>
				</ul>
				<form class="navbar-form navbar-right">
					<input type="text" class="form-control" placeholder="Search...">
				</form>
			</div>
		</div>
	</div>
	
	<div class="container<div class="row">
			<div class="col-sm-3 col-md-2 sidebar">

				<ul class="nav nav-sidebar" id="home_list">
				</ul>
				<ul class="nav nav-sidebar" id="login_list">
					
				</ul>
			</div>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				
		<?php echo $this->content; ?>
				
				
				<div id="home_title_0"></div>
					<!-- <h1 class="page-header">¿Quienes Somos?</h1> -->
					
					<div class="row placeholders">
						<div class="col-xs-6 col-sm-4 col-md-4 placeholder">
							<div class="blog-post"><!-- -------------- /.blog-post -------------- -->
					
					<!-- 			<p id="post-datde" class="">Mayo 1, 2015 por <a href="#">Abner Showman</a></p> -->
								<p id="post-datde" class=""></p>
					
								<img class="img-thumbnail img-thumbnail-profile" 
										src="<?php echo $this->basePath(); ?>/img/profile_image/logo_formal_profile_size.jpg" >
							</div><!-- -------------- /.blog-post -------------- -->
						</div>
						<div id="home_text_0" class="col-xs-6 col-sm-7 col-md-7 placeholder">
						</div>
					</div>
					
					<div id="home_title_1"></div>
					<!-- <h1 class="page-header">Contamos con el mejor servicio</h1> -->
					
					<div class="row placeholders">
						
						<div id="home_text_1" class="col-xs-6 col-sm-7 col-md-7 placeholder"></div>
						
						<div class="col-xs-6 col-sm-4 col-md-4 placeholder">
							<div class="blog-post"><!-- -------------- /.blog-post -------------- -->
					
								<img class="img-thumbnail" src="<?php echo $this->basePath(); ?>/img/galeria/eventos_especiales/big_26.jpg" >
								<h2 class=""></h2>
							</div>
						</div>
					</div>
					
					
					<h1 class="page-header">Sígenos en nuestras redes sociales</h1>
					
					<div class="row placeholders">
						<div class="col-xs-12 col-sm-12 col-md-12 placeholder">
						
							<div id="socialTimeline" style="width:100%;"> </div>
							
						</div>
					</div>
					
					<script type="text/javascript">
					
						/**
						 * Variable para llamado a peticiones jquery 
						 */
						var $basePath = "<?php echo $this->basePath();?>";
						
// 						$(document).ready(function(){
							
// 							$('#socialTimeline').dpSocialTimeline({
// 								feeds: 
// 								{
// 									'facebook_page': {data: '115869311875508'}
// 								},
// 								layoutMode: 'columns',
// 								showLayout: false,
// 								itemWidth: 200,
// 								total: 10
// 							});
							
// 						});
						
					</script>
	
					<script type="text/javascript" src="<?php echo $this->basePath()?>/js/home_module/actions.js"></script>
					<script type="text/javascript" src="<?php echo $this->basePath()?>/js/home_module/requests/home.js"></script>
				
				
				<hr>
				<footer>
					<p>&copy; 2005 - <?php echo date('Y') ?> Máxima Diversión. <?php echo $this->translate('All rights reserved.') ?></p>
				</footer>
			</div> <!-- /container -->
		</div>
	</div>
	
	<?php echo $this->inlineScript() ?>
</body>
</html>
