<div id="home_title_0"></div>
<!-- <h1 class="page-header">¿Quienes Somos?</h1> -->

<div class="row placeholders">
	<div class="col-xs-6 col-sm-4 col-md-4 placeholder">
		<div class="blog-post"><!-- -------------- /.blog-post -------------- -->

<!-- 			<p id="post-datde" class="">Mayo 1, 2015 por <a href="#">Abner Showman</a></p> -->
			<p id="post-datde" class=""></p>

			<img class="img-thumbnail img-thumbnail-profile" 
					src="<?php echo $this->basePath(); ?>/img/profile_image/logo_formal_profile_size.jpg" >
		</div><!-- -------------- /.blog-post -------------- -->
	</div>
	<div id="home_text_0" class="col-xs-6 col-sm-7 col-md-7 placeholder">
	</div>
</div>

<div id="home_title_1"></div>
<!-- <h1 class="page-header">Contamos con el mejor servicio</h1> -->

<div class="row placeholders">
	
	<div id="home_text_1" class="col-xs-6 col-sm-7 col-md-7 placeholder"></div>
	
	<div class="col-xs-6 col-sm-4 col-md-4 placeholder">
		<div class="blog-post"><!-- -------------- /.blog-post -------------- -->

			<img class="img-thumbnail" src="<?php echo $this->basePath(); ?>/img/galeria/eventos_especiales/big_26.jpg" >
			<h2 class=""></h2>
		</div>
	</div>
</div>


<h1 class="page-header">Sígenos en nuestras redes sociales</h1>

<div class="row placeholders">
	<div class="col-xs-12 col-sm-12 col-md-12 placeholder">
	
		<div id="socialTimeline" style="width:100%;"> </div>
		
	</div>
</div>

<script type="text/javascript">

	/**
	 * Variable para llamado a peticiones jquery 
	 */
	var $basePath = "<?php echo $this->basePath();?>";
	
// 	$(document).ready(function(){
		
// 		$('#socialTimeline').dpSocialTimeline({
// 			feeds: 
// 			{
// 				'facebook_page': {data: '115869311875508'}
// 			},
// 			layoutMode: 'columns',
// 			showLayout: false,
// 			itemWidth: 200,
// 			total: 10
// 		});
		
// 	});
	
</script>